name: CI-CD WebLogic Pipeline

on:
  push:
    branches:
      - main

env:
  APP_NAME: sample
  VERSION: v1.${{ github.run_number }}
  NEXUS_URL: http://192.168.182.166:8081
  NEXUS_REPO: raw-hosted

jobs:

# ===================================
# CI JOB (master-node / ci-server)
# ===================================
  build:
    name: Build WAR and Upload to Nexus
    runs-on: [self-hosted, ci-server]

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build WAR File
        run: mvn clean package -DskipTests

      - name: Rename WAR
        run: |
          cp target/*.war $APP_NAME.war

      - name: Upload WAR to Nexus
        run: |
          curl -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASS }} \
          --upload-file $APP_NAME.war \
          $NEXUS_URL/repository/$NEXUS_REPO/$APP_NAME-$VERSION.war


# ===================================
# CD JOB (worker-node / cd-server)
# ===================================
  deploy:
    name: Deploy WAR to WebLogic
    needs: build
    runs-on: [self-hosted, cd-server]

    steps:

      - name: Download WAR from Nexus
        run: |
          curl -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASS }} \
          -o app.war \
          $NEXUS_URL/repository/$NEXUS_REPO/$APP_NAME-$VERSION.war

      - name: Stop Old Application
        run: |
          java weblogic.Deployer \
          -adminurl t3://192.168.182.166:7001 \
          -username ${{ secrets.WL_USER }} \
          -password ${{ secrets.WL_PASS }} \
          -undeploy \
          -name sample || true

      - name: Deploy New WAR
        run: |
          java weblogic.Deployer \
          -adminurl t3://192.168.182.166:7001 \
          -username ${{ secrets.WL_USER }} \
          -password ${{ secrets.WL_PASS }} \
          -deploy \
          -name sample \
          -source app.war \
          -targets AdminServer

      - name: Verify Deployment
        run: |
          curl -I http://192.168.182.166:7001/sample || true
